//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquipmentRepair.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EquipmentRepairEntities : DbContext
    {
        public EquipmentRepairEntities()
            : base("name=EquipmentRepairEntities")
        {
        }
        private static EquipmentRepairEntities _context;
        public static EquipmentRepairEntities GetContext()
        {
            if (_context == null)
                _context = new EquipmentRepairEntities();

            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Division> Divisions { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<ParePart> PareParts { get; set; }
        public virtual DbSet<Repair> Repairs { get; set; }
        public virtual DbSet<Technic> Technics { get; set; }
    }
}
